### ISSUE TITLE
can't connect to version 1.13.5

### ISSUE THREAD

**Issue by mozgwar** [gordonb3/bubbagen#3]
Hi,
I get the following when I try to connect via ssh:
 ssh root@b3
The authenticity of host 'b3 (192.168.1.223)' can't be established.
ECDSA key fingerprint is SHA256:kWtiP1wAUSn4a5y/8JmsfWEV9g1Mx5SnZ8602r/CGt0.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'b3,192.168.1.223' (ECDSA) to the list of known hosts.
Connection closed by 192.168.1.223 port 22

also there is no webserver running as you can see with the output from nmap

 nmap -APn 192.168.1.223                                                                                                                                                                                      255 
Starting Nmap 7.80 ( https://nmap.org ) at 2020-03-25 10:45 EDT
Nmap scan report for b3.mozgwar.com (192.168.1.223)
Host is up (0.00082s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE VERSION
22/tcp open  ssh     OpenSSH 8.0 (protocol 2.0)
| ssh-hostkey: 
|   3072 ff:ea:49:a4:54:0b:ae:8b:1a:43:54:7d:40:d0:b7:b7 (RSA)
|   256 7b:03:5a:51:db:e6:e7:bf:cf:3f:91:82:7b:8b:ed:93 (ECDSA)
|_  256 fd:1a:47:50:55:80:05:9c:02:a0:f5:03:f8:42:7a:bd (ED25519)

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 13.86 seconds

**Comment by gordonb3** [comment]
The ssh connection closing seems more like a conflict between your client and the server. Maybe you have some left over ssh configuration files from your previous B3 installation. Two things you can try:
1. restart the B3 (use the button on the back)
2. clear the content of your `~/.ssh` folder

The distribution default exposes `ssh`, `http` and `smb` on the LAN port. If you only see `ssh` then I'm pretty sure that you connected to the WAN port.

**Comment by mozgwar** [comment]
I used another usb key and it worked correctly. I find this really weird
