### ISSUE TITLE
Boot from internal harddisk

### ISSUE THREAD

**Issue by jbekhoei** [gordonb3/bubbagen#4]
I have installed a 2TB Wester Digital WDGreen harddisk. USB  key boot, I log on via putty and run the install_to_sda.sh. Disk get the right partitions and complete the install

Any other entry quits without installing: INSTALL
Installing: check '/var/log/gentoo_install.log' in case of errors
Step 1 of 5: creating new "dos" partition table on /dev/sda...
Step 2 of 5: formatting partitions on /dev/sda...
Step 3 of 5: mounting boot and root partitions from /dev/sda...
Step 4 of 5: copying system and bootfiles (please be patient)...
grep: /boot.ini: No such file or directory
grep: /boot.ini: No such file or directory
Step 5 of 5: syncing filesystems and unmounting...

But it will not boot from harddisk.  Any advise? Thanks , Jakob

**Comment by gordonb3** [comment]
Looks like something didn't go completely right when mounting the newly created partitions on the disk. What does the install log at `/var/log/gentoo_install.log` say?

**Comment by jbekhoei** [comment]
Hi Gordon,


Get the attached when using OpenRC Ver. 1.13.0
 

Also worth knowing, I am unable to boot of USB key, following the above attempt to install to internal disk.


I have to write a new USB key to boot of USB.


Thanks


Jakob

**Comment by jbekhoei** [comment]
Hi Gordon,

Fixed! Created a root partition /dev/sda3 with a size of 40Gb

Everything is running as far as I can tell

Thanks for your help and great work,

Best regards,
 

Jakob

**Comment by gordonb3** [comment]
Glad to hear you got it solved. Unsure what caused your problems though. You say you created a 40GiB root partition, manually I presume, did you have to remove partition 3 and 4 to be able to do so or was there simply nothing there?

**Comment by jbekhoei** [comment]
Hi Gordon,

Repartitioned the whole drive by changing your partitions script default size 

The log file gave the clue… root drive came back full.

Have you done something similar for the BUBBA 2?  I am a great fan as the drives work on my sailing boat, 12VDC

Thanks and Good Week-end,

Jakob

**Comment by gordonb3** [comment]
Sorry,

Have never owned a B2, which makes it impossible for me to author this project for that device. The web based GUI management software itself should support it though and can be installed by adding `bubba` overlay to Sakaki's [gentoo-on-b2](https://github.com/sakaki-/gentoo-on-b2).

PS I took the liberty of removing your personal info from the GitHub posts above as I figured you did not intend to share these with the whole world...
